apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero1
  namespace: openshift-adp
spec:
  olm_managed: true
  enable_csi_plugin: true
  #  noobaa: true
  backupStorageLocations:
    - config:
        profile: default
        region: noobaa
        s3ForcePathStyle: "true"
        insecureSkipTLSVerify: "true"
        s3Url: https://s3-openshift-storage.apps.ocp1.example.lab
      credentials_secret_ref:
        name: cloud-credentials
        key: cloud
        namespace: openshift-adp
      name: default
      objectStorage:
        bucket: oadp
        prefix: velero
      provider: aws
      default: true
  defaultVeleroPlugins:
    - aws
    - csi
    - openshift
  velero_feature_flags: EnableCSI
  enable_restic: true
  volume_snapshot_locations:
    - config:
        profile: default
        region: "us-east-2"
      name: default
      provider: aws
