apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-clusteradmin
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
  namespace: open-cluster-management-policies
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-clusteradmin
        spec:
          remediationAction: inform # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding # role binding must exist
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: policy-clusteradmin
                subjects:
                - kind: User
                  name: admin # Name is case sensitive
                  apiGroup: rbac.authorization.k8s.io
                roleRef:
                  kind: ClusterRole #this must be Role or ClusterRole
                  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
                  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-clusteradmin
placementRef:
  name: placement-policy-clusteradmin
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-clusteradmin
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-clusteradmin
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: authenticationProfile, operator: In, values: ["htpasswd"]}
