apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-auth-provider
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: mustonlyhave
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-auth-provider
      spec:
        object-templates:
        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec:
              identityProviders:
              - htpasswd:
                  fileData:
                    name: htpass-secret
                mappingMethod: claim
                name: htpasswdidp
                type: HTPasswd
              tokenConfig:
                accessTokenMaxAgeSeconds: 7776000
        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: v1
            data:
              htpasswd: "YWRtaW46JGFwcjEkYzJGSmV6Y3ckallXb2dnN3lzRWw1TFFVOWNHb3dUMQoK"
            kind: Secret
            metadata:
              name: htpass-secret
              namespace: openshift-config
            type: Opaque
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-auth-provider
  namespace: open-cluster-management-policies
placementRef:
  name: placement-policy-oauth-provider
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-auth-provider
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-oauth-provider
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: authenticationProfile
      operator: In
      values:
      - htpasswd
    matchLabels: {}
