apiVersion: network.operator.openshift.io/v1
kind: EgressRouter
metadata:
  name: egress-router-redirect
spec:
  networkInterface: {
    macvlan: {
      mode: "Bridge"
    }
  }
  addresses: [
    {
      ip: "192.168.60.233/24",
      gateway: "192.168.60.1"
    }
  ]
  mode: Redirect
  redirect: {
    redirectRules: [
      {
        destinationIP: "192.168.60.11",
        port: 8080,
        targetPort: 80,
        protocol: TCP
      },
      {
        destinationIP: "212.77.98.9",
        port: 8081,
        targetPort: 80,
        protocol: TCP
      },
      {
        destinationIP: "99.83.207.202",
        port: 8082,
        targetPort: 80,
        protocol: TCP
      },
      {
        destinationIP: "45.32.159.226",
        port: 8083,
        targetPort: 22,
        protocol: TCP
      },
      {
        destinationIP: "45.32.159.226",
        port: 8084,
        targetPort: 80,
        protocol: TCP
      }

    ],
    fallbackIP: "192.178.25.174"
  }
