apiVersion: v1
kind: Service
metadata:
  name: egress-1
spec:
  ports:
  - name: web-app
    protocol: TCP
    port: 8080
  - name: web-app2
    protocol: TCP
    port: 8081
  - name: web-app3
    protocol: TCP
    port: 8082
  - name: redhat-tv-ssh
    port: 8083
  - name: redhat-tv-80
    port: 8084
  type: ClusterIP
  selector:
    app: egress-router-cni
