apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1-clone
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc1
