apiVersion: v1
kind: Pod
metadata:
  name: ubi8
spec:
  containers:
  - name: ubi8
    image: ubi8
    command: [ "/bin/bash", "-c", "sleep infinity" ]
    volumeMounts:
    - mountPath: /katalog
      name: test
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: pvc1
