apiVersion: v1
kind: Service
metadata:
  name: svc-lb-localpolicy
  annotations:
    metallb.universe.tf/address-pool: example1
spec:
  externalTrafficPolicy: Local
  selector:
    deployment: app-info
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
