apiVersion: v1
kind: Service
metadata:
  name: httpd-demo
spec:
  selector:           
    deployment: httpd-demo
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  externalIPs:
  - 192.168.60.235
  externalTrafficPolicy: Cluster

