apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s: 
      volumeClaimTemplate:
       spec:
         storageClassName: ovirt-csi-sc
         volumeMode: Filesystem
         resources:
           requests:
             storage: 40Gi
