apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: net-audit-role
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses/status
  - ingresses
  verbs:
  - get
  - list
  - watch
