apiVersion: v1
stringData:
  rox_central_endpoint: "central-rhacs-operator.apps.ocp1.example.lab:443"
  # The address:port tuple for StackRox Central (example - rox.stackrox.io:443)
  rox_api_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Imp3dGswIiwidHlwIjoiSldUIn0.eyJhdWQiOlsiaHR0cHM6Ly9zdGFja3JveC5pby9qd3Qtc291cmNlcyNhcGktdG9rZW5zIl0sImV4cCI6MTY4MTk4Mzg3NCwiaWF0IjoxNjUwNDQ3ODc0LCJpc3MiOiJodHRwczovL3N0YWNrcm94LmlvL2p3dCIsImp0aSI6ImRhODBhMGQ0LWQxOWYtNGIzNC1hMTZhLTg4YzQwN2NkMjAzMiIsIm5hbWUiOiJ0b2tlbmlrIiwicm9sZXMiOlsiQWRtaW4iXX0.zJU9lxgC1hqBJWUGTaTw4cVUaiYGiLl3QPUC4lrxdevDG87GZGblgqAMx6XSw9dlbzoaq3Nnp_cwsGJ2WAPvSfrXNMjgIcw8mzCtBPl0_vLxzVc4L6myvyy7YG4sPl0u3Y-SrGGwd5OHTDwHC6pY28e6EfsnFl1YmyY9s85qi_E_EHnLRljoltoHhDsttTwU4YPixcSIvWxoVYtOGmccP1zFQ7eP8_6nGF1InfPj_vKYXtQhQ0yVErXg6MEvX2S-XrxzCc9Zs5hNio1zJ9SCqHBfHIHCpkGfMicpfFDUe_BltAlnD-Ar4kEk4z43ePm-fxj7V6qsdjTj3pZvBZr0Y-fzoUN0OWMYwWm71MdhaK2G4rKrJzBXXRaKVEmzjyjDbdidQFXasJ-Ef-mkv5LiuKO0ucakRj_EdC4boAeDyGI_vwiooLnrwM6PpcdQwokqtJWAVaiXgLbhwfygklqNxx2KrOuBf04PKnTFizvk9drtcAF0ozFAigt2e08gsp6KxwNg3xiL3oBKpErewgnVhgw4DE6u20C5M6kNObPYSB6IKfdP6CfujMg6f5Qvm8PuYiaNZ6pIXe4Fu4PxuCOUwaJ4X8qjfNdANXWTtMVCt0SC5d0wHm-hTcZ3TLBgJ-sDc48feTvVOd-buGz5wklyPuoHWcbRsJL8TRYhg0nQGvQ"
  # StackRox API token with CI permissions
  # Refer to https://help.stackrox.com/docs/use-the-api/#generate-an-access-token
kind: Secret
metadata:
  name: roxsecrets
type: Opaque



