apiVersion: v1
stringData:
  rox_central_endpoint: "central-rhacs-operator.apps.ocp1.example.lab:443"
  # The address:port tuple for StackRox Central (example - rox.stackrox.io:443)
  rox_api_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Imp3dGswIiwidHlwIjoiSldUIn0.eyJhdWQiOlsiaHR0cHM6Ly9zdGFja3JveC5pby9qd3Qtc291cmNlcyNhcGktdG9rZW5zIl0sImV4cCI6MTY3NzE0NjMzNiwiaWF0IjoxNjQ1NjEwMzM2LCJpc3MiOiJodHRwczovL3N0YWNrcm94LmlvL2p3dCIsImp0aSI6IjU3MDhkZWQ4LWY5ZTEtNDc3YS1iZjQzLTdiZmNjMjY5YWM3MSIsIm5hbWUiOiJ0b2tlbiIsInJvbGVzIjpbIkFkbWluIl19.dy7tcSq_4cngdInFf5F-iWLUIV3KEhDocqbDyoPq_7hr9mDkScwYU3Oe7uQv7vMXK-cb-r8aG0qijSBN36tVD_MFY1UgV1-ocDy25e1gKG1CuODtgH5smAY4WbfX-ryiMRZOGx-POJ8F-VTWH2VSAJHTFNzr-kMq4lbXwbbZ0TfnNuPAYtqvl4kIMKeFOkZsOib6frBWH5WEW83ROdPLx1hylH6V1Fny2epyJyMcovCczUlTxLrDcfFY9d1M_-rjWTsnWQcaaU3HheixXxJ_4fDWEKz5LM1NPOCHeMB0dM8k2JjxXLCkLsPl6uQ9Dc0p1AD06dy-ztK6V03suhSt97evLUvpqyOEw_azfBdK24YSn5jCLoXXLrPHQ0wTmT_F7WVuWWBYzgaC-bF-fWH8tyVMQxi105Fk5_v6rMi3Ml9Nu5iIWWbkVTEFMEL1DGF4Ms7ly-ssO1hHPtT0YHlWA1d9tNt0N_mk5adgZbM0aqwJHwYDTKTFX2vdFECvwjhsuXFVnIyuED9b9zI0c5UDqUh-Llm-tyJsWwVHoJ23ombqU7lkKuW0YQWRv5C4DMBJeSQJ5B72otskd27cXKA4mPR6qlpDkrQrIEkUJRBsKWkrwdR5Cn_JvCSk4lXYUTjbdLmSIlQCswCHDwhHyn2H5oNSSg29jcMFpu59anJ3J68"
  # StackRox API token with CI permissions
  # Refer to https://help.stackrox.com/docs/use-the-api/#generate-an-access-token
kind: Secret
metadata:
  name: roxsecrets
type: Opaque



